import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { deleteArticle, logout, saveArticle } from './actions'

export default async function Admin() {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/admin/login')
  const { data: profile } = await supabase.from('profiles').select('role,display_name').eq('id', user.id).single()
  if (profile?.role !== 'admin') redirect('/')
  const { data: articles } = await supabase.from('articles').select('id,title,slug,status,updated_at').order('updated_at',{ascending:false})
  return <div className="mx-auto max-w-6xl px-5 py-12"><div className="flex items-center justify-between gap-6"><div><p className="text-sm text-stone-500">Painel administrativo</p><h1 className="font-serif text-4xl">Olá, {profile.display_name || 'Zeirton'}</h1></div><form action={logout}><button className="text-sm underline">Sair</button></form></div><div className="mt-10 grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><section><h2 className="font-serif text-2xl">Publicações</h2><div className="mt-5 divide-y divide-stone-200 border-y border-stone-200 dark:divide-stone-800 dark:border-stone-800">{articles?.map((a:any)=><div key={a.id} className="flex items-center justify-between gap-4 py-4"><div><strong className="font-medium">{a.title}</strong><p className="mt-1 text-xs uppercase tracking-wider text-stone-500">{a.status}</p></div><form action={deleteArticle}><input type="hidden" name="id" value={a.id}/><button className="text-sm text-red-600">Excluir</button></form></div>)}</div></section><section><h2 className="font-serif text-2xl">Novo artigo</h2><form action={saveArticle} className="mt-5 space-y-4"><input name="title" required placeholder="Título" className="w-full border bg-transparent px-4 py-3 dark:border-stone-700"/><input name="slug" required placeholder="slug-do-artigo" className="w-full border bg-transparent px-4 py-3 dark:border-stone-700"/><input name="subtitle" placeholder="Subtítulo" className="w-full border bg-transparent px-4 py-3 dark:border-stone-700"/><textarea name="excerpt" placeholder="Resumo" rows={3} className="w-full border bg-transparent px-4 py-3 dark:border-stone-700"/><textarea name="content_html" required placeholder="Conteúdo em HTML" rows={14} className="w-full border bg-transparent px-4 py-3 font-mono text-sm dark:border-stone-700"/><textarea name="references_text" placeholder="Referências e fontes" rows={4} className="w-full border bg-transparent px-4 py-3 dark:border-stone-700"/><select name="status" className="w-full border bg-transparent px-4 py-3 dark:border-stone-700"><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="scheduled">Agendado</option><option value="archived">Arquivado</option></select><button className="w-full bg-stone-900 px-5 py-3 text-white dark:bg-white dark:text-stone-950">Salvar artigo</button></form></section></div></div>
}
